spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  topic:
    foo: test-topic
  kafka:
    enabled: true

logging:
  level:
    root: ERROR
#    org.springframework.web: ERROR
#    org.springframework.kafka: DEBUG
#    net.eleven: DEBUG